### ISSUE TITLE
Permission denied when trying to access ApiController

### ISSUE THREAD

**Issue by kader-hlby** [LaravelDaily/api-generator#1]
after running the make:api command both controller and routes are generated , but when i try to access the ApiController through my editor or the finder it says permission denied.

**Comment by ModestasV** [comment]
Hey, can you give us more details?

Would be nice to know:
- Operating system
- Permissions of the file (` ls -l ` in the directory where the file is)

Thank you

**Comment by kader-hlby** [comment]
Mac Os 10
ls -l in the directory where the file is:
d-wxr----x  3 abdulkaderalhalaby  staff  102 Aug  4 11:20 Api
drwxr-xr-x  6 abdulkaderalhalaby  staff  204 Aug  4 10:45 Auth
-rw-r--r--  1 abdulkaderalhalaby  staff  361 Aug  4 10:45 Controller.php

**Comment by ModestasV** [comment]
@kader-hlby Go into the Api directory and to the same. But seems like our teammate got the folder permissions wrong from the first sigh.

**Comment by kader-hlby** [comment]
➜  Api ls -l
ls: .: Permission denied
➜  Api sudo ls -l
-rw-r--r--  1 abdulkaderalhalaby  staff  741 Aug  4 11:20 TasksController.php

**Comment by KarolisNarkevicius** [comment]
just change permissions of Api directory to 775
`sudo chmod -R 775 Api`
and it should be fine

**Comment by kader-hlby** [comment]
thanks , it works , so if we want to change it from inside the project 
should we change it here also?

            mkdir(base_path('app/Http/Controllers/Api'), 755);

this is from `ApiControllerGenerator` create function

**Comment by ModestasV** [comment]
@kader-hlby Wait for @PovilasKorop to push out a new version of the package and you will be able to update it via composer :)

**Comment by kader-hlby** [comment]
ok , thanks .

**Comment by PovilasKorop** [comment]
@kader-hlby ok released new version 0.1.5 with the fix, run `composer update`
