### ISSUE TITLE
Installation request for laravel/framework (locked at v5.8.37, required as 5.8.*) -> satisfiable by laravel/framework[v5.8.37]

### ISSUE THREAD

**Issue by herquiloidehele** [LaravelDaily/api-generator#10]
I can't install package on Laravel Framework 5.8.37.

![Screenshot 2020-05-02 21 14 10](https://user-images.githubusercontent.com/23740775/80873580-f118e380-8cb9-11ea-9db8-2e7dc47329c2.png)

**Comment by PovilasKorop** [comment]
@herquiloidehele we haven't updated the package to support that version, sorry, it's an old package. Now we're focused on - building APIs in our laravel generator at www.quickadminpanel.com

**Comment by herquiloidehele** [comment]
Alright, thank you.
