### ISSUE TITLE
Laravel 5.5 no working

### ISSUE THREAD

**Issue by zkmark** [LaravelDaily/api-generator#3]
Will be updated for version 5.5?
show this message

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for laraveldaily/apigenerator ^0.1.5 -> satisfiable by laraveldaily/apigenerator[0.1.5].
    - laraveldaily/apigenerator 0.1.5 requires laravel/framework 5.4.* -> satisfiable by laravel/framework[5.4.x-dev, v5.4.0, v5.4.1, v5.4.10, v5.4.11, v5.4.12, v5.4.13, v5.4.14, v5.4.15, v5.4.16, v5.4.17, v5.4.18, v5.4.19, v5.4.2, v5.4.20, v5.4.21, v5.4.22, v5.4.23, v5.4.24, v5.4.25, v5.4.26, v5.4.27, v5.4.28, v5.4.29, v5.4.3, v5.4.30, v5.4.31, v5.4.32, v5.4.33, v5.4.34, v5.4.35, v5.4.36, v5.4.4, v5.4.5, v5.4.6, v5.4.7, v5.4.8, v5.4.9] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by PovilasKorop** [comment]
@ztvMark we haven't updated it to 5.5 yet, we'll probably do it in upcoming 1-2 weeks.

**Comment by PovilasKorop** [comment]
@ztvMark released a new version compatible with Laravel 5.5.

**Comment by ghost** [comment]
hi, is there plans to update for 5.6?

**Comment by PovilasKorop** [comment]
@JDias thanks for reminding, will do this week.
