### ISSUE TITLE
Suggestion: Option to specify a Model folder

### ISSUE THREAD

**Issue by marcelo-tavares** [LaravelDaily/api-generator#4]
As we can put our model classes files inside a folder under App, what about to provide an option to specify this folder? It can have a default value (App/Models, for instance). 

If omitted models should be in App folder.
If informed "\apigenerator\src\Commands\GenerateApiCommand.php" should use it to create the value for $modelPath variable (line 46)
usage:
--modelPath[=App/Models] 

Congrats for the package. It is very usefull!

**Comment by PovilasKorop** [comment]
Thought about it, and there may be even more settings for more folders. But, to be honest, we didn't plan to expand this package for more cases, our time is pretty limited. So, at the moment, if you submit a pull request, we're happy to accept and merge it.
