### ISSUE TITLE
APIDoc

### ISSUE THREAD

**Issue by ghost** [LaravelDaily/api-generator#5]
Im really new to this all, i found this package, and as it says its ok suggestions, i will give one even if im not sure if it fits.

Could api-generator have some support for running https://github.com/mpociot/laravel-apidoc-generator ?

im with laravel 5.6, and starting on this, and im thinking of use this 2 packages to help me build some nice apis! :)

**Comment by PovilasKorop** [comment]
@JDias Currently we're not planning to invest much time into this package. But you can use it to generate API Controllers, then add your own comments on top of methods, and then generate Docs.

**Comment by ghost** [comment]
Thanks, that is my actual plan!

i was sharing cause maybe would be simple to add some "support" for it as guidance for newcomers like me. (i will probably start to envolve the generated files later, was just sharing an ideia) :)

Regards!
